Added command for creating UP.

diff --git a/bin/um b/bin/um
--- a/bin/um
+++ b/bin/um
@@ -10,6 +10,22 @@ if [ "$#" -lt 1 ]; then
 fi
 
 case "$1" in
+"create_up")
+	if [ "$#" -ne 2 ]; then
+		echo "[!] missing #SR" >&2
+		exit 3
+	fi
+	if [[ ! $2 =~ ^[0-9]{6}$ ]]; then
+		echo "[!] SR should be a 6-digit number" >&2
+		exit 4
+	fi
+	echo "[i] isc omg pi --new $2"
+	read -p "[?] Are you sure? " -n 1 -r
+	echo
+	if [[ "$REPLY" =~ ^[yY]$ ]]; then
+		$isc omg pi --new "$2"
+	fi
+;;
 "revoke_rr")
 	if [ "$#" -ne 2 ]; then
 		echo "[!] missing #RR" >&2
