Added RR creation.

diff --git a/bin/um b/bin/um
--- a/bin/um
+++ b/bin/um
@@ -73,6 +73,22 @@ case "$1" in
 	echo "$?:"
 	echo "$result"
 ;;
+"create_rr")
+	if [ "$#" -ne 2]; then
+		echo "[!] missing #UP" >&2
+		exit 3
+	fi
+	if [[ ! $2 =~ ^[0-9]{5}$ ]]; then
+		echo "[!] UP should be a 5-digit number" >&2
+		exit 4
+	fi
+	echo "[i] isc omg rr --incident $2"
+	read -p "[?] Are you sure? " -n 1 -r
+	echo
+	if [[ "$REPLY" =~ ^[yY]$ ]]; then
+		$($isc omg rr --incident "$2")
+	fi
+;;
 *)
 	echo "[!] unsupported op" >&2
 	exit 2
